# Generated by Django 4.1.3 on 2023-01-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_thumbnail', models.ImageField(upload_to='templates-thumbnails')),
                ('template_name', models.CharField(max_length=100)),
                ('html_file', models.FileField(upload_to='./templates')),
            ],
        ),
    ]
