# Generated by Django 4.1.2 on 2022-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_thumbnail', models.ImageField(upload_to='PDF-Templates')),
                ('template_name', models.CharField(max_length=100)),
                ('html_file', models.FileField(upload_to='templates')),
            ],
        ),
    ]
