# Generated by Django 4.1.2 on 2022-11-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftemplate',
            name='html_file',
            field=models.FileField(upload_to='./templates'),
        ),
    ]
