# Generated by Django 4.1.2 on 2022-11-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_pdftemplate_html_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftemplate',
            name='template_thumbnail',
            field=models.ImageField(upload_to='templates-thumbnails'),
        ),
    ]
