# Generated by Django 4.1.2 on 2022-11-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_alter_profile_avatar_alter_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cell',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='companies'),
        ),
    ]
