# Generated by Django 4.1.3 on 2022-12-07 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0003_profile_cell_alter_experience_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='company_logo',
        ),
    ]
