# Generated by Django 4.1.3 on 2023-01-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0004_remove_experience_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=' write your professional summery here '),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cell',
            field=models.CharField(default='-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='-', max_length=300),
        ),
    ]
